User.create(name: :Ivan, email: "ivan@gmail.com", password: "123", password_confirmation: "123")

User.create(name: :Ivan, email: "ivan@gmail.com", password: "123")

Pokemon.create(name: :Bulbasaur, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/001-Bulbasaur-icon.png")
Pokemon.create(name: :Ivysaur, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/002-Ivysaur-icon.png")
Pokemon.create(name: :Venusaur, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/003-Venusaur-icon.png")
Pokemon.create(name: :Charmander, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/004-Charmander-icon.png")
Pokemon.create(name: :Charmeleon, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/005-Charmeleon-icon.png")
Pokemon.create(name: :Charizard, primary_type: :Fire, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/006-Charizard-icon.png")
Pokemon.create(name: :Squirtle, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/007-Squirtle-icon.png")
Pokemon.create(name: :Wartortle, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/008-Wartortle-icon.png")
Pokemon.create(name: :Blastoise, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/009-Blastoise-icon.png")
Pokemon.create(name: :Caterpie, primary_type: :Bug, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/010-Caterpie-icon.png")
Pokemon.create(name: :Metapod, primary_type: :Bug, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/011-Metapod-icon.png")
Pokemon.create(name: :Butterfree, primary_type: :Bug, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/012-Butterfree-icon.png")
Pokemon.create(name: :Weedle, primary_type: :Bug, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/013-Weedle-icon.png")
Pokemon.create(name: :Kakuna, primary_type: :Bug, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/014-Kakuna-icon.png")
Pokemon.create(name: :Beedrill, primary_type: :Bug, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/015-Beedrill-icon.png")
Pokemon.create(name: :Pidgey, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/016-Pidgey-icon.png")
Pokemon.create(name: :Pidgeotto, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/017-Pidgeotto-icon.png")
Pokemon.create(name: :Pidgeot, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/018-Pidgeot-icon.png")
Pokemon.create(name: :Rattata, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/019-Rattata-icon.png")
Pokemon.create(name: :Raticate, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/020-Raticate-icon.png")
Pokemon.create(name: :Spearow, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/021-Spearow-icon.png")
Pokemon.create(name: :Fearow, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/022-Fearow-icon.png")
Pokemon.create(name: :Ekans, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/023-Ekans-icon.png")
Pokemon.create(name: :Arbok, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/024-Arbok-icon.png")
Pokemon.create(name: :Pikachu, primary_type: :Electric, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/025-Pikachu-icon.png")
Pokemon.create(name: :Raichu, primary_type: :Electric, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/026-Raichu-icon.png")
Pokemon.create(name: :Sandshrew, primary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/027-Sandshrew-icon.png")
Pokemon.create(name: :Sandslash, primary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/028-Sandslash-icon.png")
Pokemon.create(name: :Nidoran♀, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/029-Nidoran-icon.png")
Pokemon.create(name: :Nidorina, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/030-Nidorina-icon.png")
Pokemon.create(name: :Nidoqueen, primary_type: :Poison, secondary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/031-Nidoqueen-icon.png")
Pokemon.create(name: :Nidoran♂, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/032-Nidorano-icon.png")
Pokemon.create(name: :Nidorino, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/033-Nidorino-icon.png")
Pokemon.create(name: :Nidoking, primary_type: :Poison, secondary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/034-Nidoking-icon.png")
Pokemon.create(name: :Clefairy, primary_type: :Fairy, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/035-Clefairy-icon.png")
Pokemon.create(name: :Clefable, primary_type: :Fairy, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/036-Clefable-icon.png")
Pokemon.create(name: :Vulpix, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/037-Vulpix-icon.png")
Pokemon.create(name: :Ninetales, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/038-Ninetales-icon.png")
Pokemon.create(name: :Jigglypuff, primary_type: :Normal, secondary_type: :Fairy, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/039-Jigglypuff-icon.png")
Pokemon.create(name: :Wigglytuff, primary_type: :Normal, secondary_type: :Fairy, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/040-Wigglytuff-icon.png")
Pokemon.create(name: :Zubat, primary_type: :Poison, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/041-Zubat-icon.png")
Pokemon.create(name: :Golbat, primary_type: :Poison, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/042-Golbat-icon.png")
Pokemon.create(name: :Oddish, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/043-Oddish-icon.png")
Pokemon.create(name: :Gloom, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/044-Gloom-icon.png")
Pokemon.create(name: :Vileplume, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/045-Vileplume-icon.png")
Pokemon.create(name: :Paras, primary_type: :Bug, secondary_type: :Grass, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/046-Paras-icon.png")
Pokemon.create(name: :Parasect, primary_type: :Bug, secondary_type: :Grass, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/047-Parasect-icon.png")
Pokemon.create(name: :Venonat, primary_type: :Bug, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/048-Venonat-icon.png")
Pokemon.create(name: :Venomoth, primary_type: :Bug, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/049-Venomoth-icon.png")
Pokemon.create(name: :Diglett, primary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/050-Diglett-icon.png")
Pokemon.create(name: :Dugtrio, primary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/051-Dugtrio-icon.png")
Pokemon.create(name: :Meowth, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/052-Meowth-icon.png")
Pokemon.create(name: :Persian, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/053-Persian-icon.png")
Pokemon.create(name: :Psyduck, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/054-Psyduck-icon.png")
Pokemon.create(name: :Golduck, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/055-Golduck-icon.png")
Pokemon.create(name: :Mankey, primary_type: :Fighting, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/056-Mankey-icon.png")
Pokemon.create(name: :Primeape, primary_type: :Fighting, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/057-Primeape-icon.png")
Pokemon.create(name: :Growlithe, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/058-Growlithe-icon.png")
Pokemon.create(name: :Arcanine, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/059-Arcanine-icon.png")
Pokemon.create(name: :Poliwag, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/060-Poliwag-icon.png")
Pokemon.create(name: :Poliwhirl, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/061-Poliwhirl-icon.png")
Pokemon.create(name: :Poliwrath, primary_type: :Water, secondary_type: :Fighting, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/062-Poliwrath-icon.png")
Pokemon.create(name: :Abra, primary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/063-Abra-icon.png")
Pokemon.create(name: :Kadabra, primary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/064-Kadabra-icon.png")
Pokemon.create(name: :Alakazam, primary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/065-Alakazam-icon.png")
Pokemon.create(name: :Machop, primary_type: :Fighting, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/066-Machop-icon.png")
Pokemon.create(name: :Machoke, primary_type: :Fighting, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/067-Machoke-icon.png")
Pokemon.create(name: :Machamp, primary_type: :Fighting, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/068-Machamp-icon.png")
Pokemon.create(name: :Bellsprout, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/069-Bellsprout-icon.png")
Pokemon.create(name: :Weepinbell, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/070-Weepinbell-icon.png")
Pokemon.create(name: :Victreebel, primary_type: :Grass, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/071-Victreebel-icon.png")
Pokemon.create(name: :Tentacool, primary_type: :Water, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/072-Tentacool-icon.png")
Pokemon.create(name: :Tentacruel, primary_type: :Water, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/073-Tentacruel-icon.png")
Pokemon.create(name: :Geodude, primary_type: :Rock, secondary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/074-Geodude-icon.png")
Pokemon.create(name: :Graveler, primary_type: :Rock, secondary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/075-Graveler-icon.png")
Pokemon.create(name: :Golem, primary_type: :Rock, secondary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/076-Golem-icon.png")
Pokemon.create(name: :Ponyta, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/077-Ponyta-icon.png")
Pokemon.create(name: :Rapidash, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/078-Rapidash-icon.png")
Pokemon.create(name: :Slowpoke, primary_type: :Water, secondary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/079-Slowpoke-icon.png")
Pokemon.create(name: :Slowbro, primary_type: :Water, secondary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/080-Slowbro-icon.png")
Pokemon.create(name: :Magnemite, primary_type: :Electric, secondary_type: :Steel, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/081-Magnemite-icon.png")
Pokemon.create(name: :Magneton, primary_type: :Electric, secondary_type: :Steel, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/082-Magneton-icon.png")
Pokemon.create(name: :Farfetchd, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/083-Farfetchd-icon.png")
Pokemon.create(name: :Doduo, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/084-Doduo-icon.png")
Pokemon.create(name: :Dodrio, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/085-Dodrio-icon.png")
Pokemon.create(name: :Dodrio, primary_type: :Normal, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/085-Dodrio-icon.png")
Pokemon.create(name: :Seel, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/086-Seel-icon.png")
Pokemon.create(name: :Dewgong, primary_type: :Water, secondary_type: :Ice, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/087-Dewgong-icon.png")
Pokemon.create(name: :Grimer, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/088-Grimer-icon.png")
Pokemon.create(name: :Muk, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/089-Muk-icon.png")
Pokemon.create(name: :Shellder, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/090-Shellder-icon.png")
Pokemon.create(name: :Cloyster, primary_type: :Water, secondary_type: :Ice, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/091-Cloyster-icon.png")
Pokemon.create(name: :Gastly, primary_type: :Ghost, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/092-Gastly-icon.png")
Pokemon.create(name: :Haunter, primary_type: :Ghost, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/093-Haunter-icon.png")
Pokemon.create(name: :Gengar, primary_type: :Ghost, secondary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/094-Gengar-icon.png")
Pokemon.create(name: :Onix, primary_type: :Rock, secondary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/095-Onix-icon.png")
Pokemon.create(name: :Drowzee, primary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/096-Drowzee-icon.png")
Pokemon.create(name: :Hypno, primary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/097-Hypno-icon.png")
Pokemon.create(name: :Krabby, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/098-Krabby-icon.png")
Pokemon.create(name: :Kingler, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/099-Kingler-icon.png")
Pokemon.create(name: :Voltorb, primary_type: :Electric, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/100-Voltorb-icon.png")
Pokemon.create(name: :Electrode, primary_type: :Electric, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/101-Electrode-icon.png")
Pokemon.create(name: :Exeggcute, primary_type: :Grass, secondary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/102-Exeggcute-icon.png")
Pokemon.create(name: :Exeggutor, primary_type: :Grass, secondary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/103-Exeggutor-icon.png")
Pokemon.create(name: :Cubone, primary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/104-Cubone-icon.png")
Pokemon.create(name: :Marowak, primary_type: :Ground, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/105-Marowak-icon.png")
Pokemon.create(name: :Hitmonlee, primary_type: :Fighting, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/106-Hitmonlee-icon.png")
Pokemon.create(name: :Hitmonchan, primary_type: :Fighting, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/107-Hitmonchan-icon.png")
Pokemon.create(name: :Lickitung, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/108-Lickitung-icon.png")
Pokemon.create(name: :Koffing, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/109-Koffing-icon.png")
Pokemon.create(name: :Weezing, primary_type: :Poison, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/110-Weezing-icon.png")
Pokemon.create(name: :Rhyhorn, primary_type: :Ground, secondary_type: :Rock, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/111-Rhyhorn-icon.png")
Pokemon.create(name: :Rhydon, primary_type: :Ground, secondary_type: :Rock, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/112-Rhydon-icon.png")
Pokemon.create(name: :Chansey, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/113-Chansey-icon.png")
Pokemon.create(name: :Tangela, primary_type: :Grass, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/114-Tangela-icon.png")
Pokemon.create(name: :Kangaskhan, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/115-Kangaskhan-icon.png")
Pokemon.create(name: :Horsea, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/116-Horsea-icon.png")
Pokemon.create(name: :Seadra, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/117-Seadra-icon.png")
Pokemon.create(name: :Goldeen, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/118-Goldeen-icon.png")
Pokemon.create(name: :Seaking, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/119-Seaking-icon.png")
Pokemon.create(name: :Staryu, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/120-Staryu-icon.png")
Pokemon.create(name: :Starmie, primary_type: :Water, secondary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/121-Starmie-icon.png")
Pokemon.create(name: :MrMime, primary_type: :Psychic, secondary_type: :Fairy, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/122-Mr-Mime-icon.png")
Pokemon.create(name: :Scyther, primary_type: :Bug, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/123-Scyther-icon.png")
Pokemon.create(name: :Jynx, primary_type: :Ice, secondary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/124-Jynx-icon.png")
Pokemon.create(name: :Electabuzz, primary_type: :Electric, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/125-Electabuzz-icon.png")
Pokemon.create(name: :Magmar, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/126-Magmar-icon.png")
Pokemon.create(name: :Pinsir, primary_type: :Bug, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/127-Pinsir-icon.png")
Pokemon.create(name: :Tauros, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/128-Tauros-icon.png")
Pokemon.create(name: :Magikarp, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/129-Magikarp-icon.png")
Pokemon.create(name: :Gyarados, primary_type: :Water, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/130-Gyarados-icon.png")
Pokemon.create(name: :Lapras, primary_type: :Water, secondary_type: :Ice, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/131-Lapras-icon.png")
Pokemon.create(name: :Ditto, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/132-Ditto-icon.png")
Pokemon.create(name: :Eevee, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/133-Eevee-icon.png")
Pokemon.create(name: :Vaporeon, primary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/134-Vaporeon-icon.png")
Pokemon.create(name: :Jolteon, primary_type: :Electric, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/135-Jolteon-icon.png")
Pokemon.create(name: :Flareon, primary_type: :Fire, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/136-Flareon-icon.png")
Pokemon.create(name: :Porygon, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/137-Porygon-icon.png")
Pokemon.create(name: :Omanyte, primary_type: :Rock, secondary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/138-Omanyte-icon.png")
Pokemon.create(name: :Omastar, primary_type: :Rock, secondary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/139-Omastar-icon.png")
Pokemon.create(name: :Kabuto, primary_type: :Rock, secondary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/140-Kabuto-icon.png")
Pokemon.create(name: :Kabutops, primary_type: :Rock, secondary_type: :Water, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/141-Kabutops-icon.png")
Pokemon.create(name: :Aerodactyl, primary_type: :Rock, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/142-Aerodactyl-icon.png")
Pokemon.create(name: :Snorlax, primary_type: :Normal, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/143-Snorlax-icon.png")
Pokemon.create(name: :Articuno, primary_type: :Ice, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/144-Articuno-icon.png")
Pokemon.create(name: :Zapdos, primary_type: :Electric, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/145-Zapdos-icon.png")
Pokemon.create(name: :Moltres, primary_type: :Fire, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/146-Moltres-icon.png")
Pokemon.create(name: :Dratini, primary_type: :Dragon, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/147-Dratini-icon.png")
Pokemon.create(name: :Dragonair, primary_type: :Dragon, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/148-Dragonair-icon.png")
Pokemon.create(name: :Dragonite, primary_type: :Dragon, secondary_type: :Flying, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/149-Dragonite-icon.png")
Pokemon.create(name: :Mewtwo, primary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/150-Mewtwo-icon.png")
Pokemon.create(name: :Mew, primary_type: :Psychic, photo_url: "http://icons.iconarchive.com/icons/hektakun/pokemon/72/151-Mew-icon.png")


TeamMember.create(team_id: 1, pokemon_id: 1)
TeamMember.create(team_id: 1, pokemon_id: 4)
TeamMember.create(team_id: 1, pokemon_id: 7)

Team.create(user_id: 1)

TeamMember.create(team_id: 2, pokemon_id: 2)
TeamMember.create(team_id: 2, pokemon_id: 5)
TeamMember.create(team_id: 2, pokemon_id: 8)

Team.create(user_id: 1)

TeamMember.create(team_id: 3, pokemon_id: 3)
TeamMember.create(team_id: 3, pokemon_id: 6)
TeamMember.create(team_id: 3, pokemon_id: 9)

Team.create(user_id: 1)